version: "3.9" 
networks: 
  my-overlay-network:
    external: true
    driver: overlay
    attachable: true

services: 
  crawler-news-covid:
    image: hieuopntechiz/crawler-news-covid:1.0.0
    ports: 
      - "5000:5000"
    depends_on: 
      - mongodb
    restart: unless-stopped
    networks: 
      - "my-overlay-network"
  
  crawler-news-covid-1:
    image: hieuopntechiz/crawler-news-covid-1:1.0.0
    ports: 
      - "3000:3000"
    restart: unless-stopped
    networks: 
      - "my-overlay-network"

  crawler-news-covid-2:
    image: hieuopntechiz/crawler-news-covid-2:1.0.0
    depends_on: 
      - crawler-news-covid
    ports: 
      - "3001:3001"
    restart: unless-stopped
    networks: 
      - "my-overlay-network"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=crawler
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      # seeding scripts
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      # named volumes
      - ./mongodb:/data/db
    restart: unless-stopped
    networks: 
      - "my-overlay-network"
  adminer:
    image: dockette/adminer:mongo
    restart: always
    depends_on: 
      - mongodb
    ports:
      - 8000:80
    networks: 
      - "my-overlay-network"
