version: "3.9" 
services: 
  crawler-news-covid:
    image: crawler-news-covid:v1.0.6
    ports: 
      - "5000:5000"
    depends_on: 
      - mongodb
    restart: unless-stopped
  
  crawler-news-covid-1:
    image: crawler-news-covid-1:v1.0.3
    ports: 
      - "3000:3000"
    restart: unless-stopped

  crawler-news-covid-2:
    image: crawler-news-covid-2:v1.0.5
    depends_on: 
      - crawler-news-covid
    ports: 
      - "3001:3001"
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=crawler
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      # seeding scripts
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      # named volumes
      - ./mongodb:/data/db
    restart: unless-stopped